services:
  - type: web
    name: primedrive
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /sign-up
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
        value: /
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
        value: /
      - key: FROM_EMAIL
        value: onboarding@resend.dev
      - key: ADMIN_EMAIL
        value: admin@cyber-trouble.de
      - key: RESEND_NOTIFY_EMAIL
        value: sbt2309@gmail.com
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: primedrive
          property: host
      - key: OPENCAGE_API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
